=== broapplication/pd2-sisto/Assignment1/bin/dtd/wfInfo.dtd
<!ELEMENT workflowMonitor 	(workflow*)>

<!ELEMENT workflow 				(action+,process*)>
<!ATTLIST workflow
	name 						NMTOKEN 		#REQUIRED>
		
<!ELEMENT action 			(simpleAction|processAction)>
<!ATTLIST action
	name 						NMTOKEN 			#REQUIRED
	automaticallyIstantiated 	(true|false) 	"false"
	role 						CDATA			#REQUIRED>
	
<!ELEMENT simpleAction 		EMPTY>
<!ATTLIST simpleAction
	possibleNextActions			NMTOKENS			#IMPLIED>
	
<!ELEMENT processAction 		EMPTY>
<!ATTLIST processAction
	actionWorkflow				NMTOKEN			#REQUIRED>

<!ELEMENT process 			(actionStatus*)>
<!ATTLIST process
	startTime					CDATA			#REQUIRED>

<!ELEMENT actionStatus 		(actor*)>
<!ATTLIST actionStatus
	action						NMTOKEN			#REQUIRED
	terminationTime				CDATA			#IMPLIED>
	
<!ELEMENT actor EMPTY>
<!ATTLIST actor
	name						CDATA			#REQUIRED
	role						CDATA			#REQUIRED>

=== broapplication/pd2-sisto/Assignment2/dtd/wfInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE workflowMonitor SYSTEM "wfInfo.dtd">
<workflowMonitor>
   <workflow name="RedazioneArticolo">
      <action automaticallyIstantiated="false" name="Pubblicazione" role="Redattore">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="false" name="Revisione" role="Giornalista">
         <simpleAction possibleNextActions="Controllo"/>
      </action>
      <action automaticallyIstantiated="true" name="Scrittura" role="Giornalista">
         <simpleAction possibleNextActions="Controllo"/>
      </action>
      <action automaticallyIstantiated="false" name="Controllo" role="Redattore">
         <simpleAction possibleNextActions="Revisione Pubblicazione"/>
      </action>
      <process startTime="15/01/2008 19:26 CET">
         <actionStatus action="Scrittura" terminationTime="15/01/2008 20:53 CET">
            <actor name="Francesca Rossi" role="Giornalista"/>
         </actionStatus>
         <actionStatus action="Controllo" terminationTime="17/01/2008 12:17 CET">
            <actor name="Enrico Maria Rossi" role="Redattore"/>
         </actionStatus>
         <actionStatus action="Pubblicazione" terminationTime="18/01/2008 17:45 CET">
            <actor name="Enrico Maria Rossi" role="Redattore"/>
         </actionStatus>
      </process>
      <process startTime="05/02/2008 15:18 CET">
         <actionStatus action="Scrittura"/>
      </process>
      <process startTime="18/01/2008 00:10 CET">
         <actionStatus action="Scrittura" terminationTime="18/01/2008 05:28 CET">
            <actor name="Giovanni Gonzales" role="Giornalista"/>
         </actionStatus>
         <actionStatus action="Controllo" terminationTime="19/01/2008 06:48 CET">
            <actor name="Enrico Maria Rossi" role="Redattore"/>
         </actionStatus>
         <actionStatus action="Pubblicazione" terminationTime="20/01/2008 16:19 CET">
            <actor name="Mario Fumagalli" role="Redattore"/>
         </actionStatus>
      </process>
      <process startTime="26/01/2008 06:35 CET">
         <actionStatus action="Scrittura" terminationTime="28/01/2008 03:18 CET">
            <actor name="Giuseppe Castiglia" role="Giornalista"/>
         </actionStatus>
         <actionStatus action="Controllo" terminationTime="28/01/2008 17:57 CET">
            <actor name="Enrico Maria Rossi" role="Redattore"/>
         </actionStatus>
         <actionStatus action="Pubblicazione" terminationTime="29/01/2008 13:43 CET">
            <actor name="Mario Del Santo" role="Redattore"/>
         </actionStatus>
      </process>
      <process startTime="17/01/2008 05:56 CET">
         <actionStatus action="Scrittura"/>
      </process>
   </workflow>
   <workflow name="VenditaNormale">
      <action automaticallyIstantiated="true" name="ConsegnaMerce" role="Magazziniere">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
         <simpleAction possibleNextActions="RicezPagamento"/>
      </action>
      <action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
         <simpleAction/>
      </action>
      <process startTime="15/01/2008 13:17 CET">
         <actionStatus action="ConsegnaMerce" terminationTime="16/01/2008 11:44 CET">
            <actor name="Enrica Neri" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura" terminationTime="18/01/2008 11:33 CET">
            <actor name="Carol Vicentini" role="Contabile"/>
         </actionStatus>
         <actionStatus action="RicezPagamento" terminationTime="18/01/2008 21:06 CET">
            <actor name="Carol Vicentini" role="Contabile"/>
         </actionStatus>
      </process>
      <process startTime="08/02/2008 16:34 CET">
         <actionStatus action="ConsegnaMerce" terminationTime="09/02/2008 12:22 CET">
            <actor name="Sonia Silvestri" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura" terminationTime="10/02/2008 18:59 CET">
            <actor name="Andrea Lanfranco" role="Contabile"/>
         </actionStatus>
         <actionStatus action="RicezPagamento" terminationTime="11/02/2008 02:43 CET">
            <actor name="Andrea Lanfranco" role="Contabile"/>
         </actionStatus>
      </process>
      <process startTime="14/01/2008 13:15 CET">
         <actionStatus action="ConsegnaMerce"/>
         <actionStatus action="EmissFattura"/>
      </process>
      <process startTime="09/02/2008 21:22 CET">
         <actionStatus action="ConsegnaMerce" terminationTime="12/02/2008 17:51 CET">
            <actor name="Enrica Neri" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura" terminationTime="11/02/2008 20:29 CET">
            <actor name="Carol Vicentini" role="Contabile"/>
         </actionStatus>
         <actionStatus action="RicezPagamento"/>
      </process>
      <process startTime="12/01/2008 18:36 CET">
         <actionStatus action="ConsegnaMerce" terminationTime="13/01/2008 08:38 CET">
            <actor name="Claude Prisco" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura">
            <actor name="Carol Vicentini" role="Contabile"/>
         </actionStatus>
      </process>
   </workflow>
   <workflow name="GestioneVendita">
      <action automaticallyIstantiated="false" name="VenditaNormale" role="RespVendite">
         <processAction actionWorkflow="VenditaNormale"/>
      </action>
      <action automaticallyIstantiated="true" name="AccettazOrdine" role="AddettoVendite">
         <simpleAction possibleNextActions="VenditaPagAnt VenditaNormale"/>
      </action>
      <action automaticallyIstantiated="false" name="VenditaPagAnt" role="RespVendite">
         <processAction actionWorkflow="VenditaPagAnt"/>
      </action>
      <process startTime="02/02/2008 19:56 CET">
         <actionStatus action="AccettazOrdine" terminationTime="04/02/2008 00:07 CET">
            <actor name="Giovanni Francese" role="AddettoVendite"/>
         </actionStatus>
         <actionStatus action="VenditaNormale" terminationTime="05/02/2008 07:49 CET">
            <actor name="Mauro Perissino" role="RespVendite"/>
         </actionStatus>
      </process>
      <process startTime="30/01/2008 10:31 CET">
         <actionStatus action="AccettazOrdine" terminationTime="01/02/2008 03:13 CET">
            <actor name="Riccardo Bianchi" role="AddettoVendite"/>
         </actionStatus>
         <actionStatus action="VenditaNormale" terminationTime="01/02/2008 22:23 CET">
            <actor name="Pippo Silvestri" role="RespVendite"/>
         </actionStatus>
      </process>
      <process startTime="14/01/2008 20:50 CET">
         <actionStatus action="AccettazOrdine" terminationTime="16/01/2008 13:49 CET">
            <actor name="Riccardo Bianchi" role="AddettoVendite"/>
         </actionStatus>
         <actionStatus action="VenditaPagAnt" terminationTime="18/01/2008 04:04 CET">
            <actor name="Mario De Vitis" role="RespVendite"/>
         </actionStatus>
      </process>
   </workflow>
   <workflow name="VenditaPagAnt">
      <action automaticallyIstantiated="false" name="ConsegnaMerce" role="Magazziniere">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
         <simpleAction possibleNextActions="ConsegnaMerce"/>
      </action>
      <action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
         <simpleAction possibleNextActions="RicezPagamento"/>
      </action>
      <process startTime="28/01/2008 00:11 CET">
         <actionStatus action="EmissFattura" terminationTime="29/01/2008 05:34 CET">
            <actor name="Francesco Messina" role="Contabile"/>
         </actionStatus>
         <actionStatus action="RicezPagamento" terminationTime="29/01/2008 06:52 CET">
            <actor name="Mario Lamarmora" role="Contabile"/>
         </actionStatus>
         <actionStatus action="ConsegnaMerce" terminationTime="31/01/2008 05:58 CET">
            <actor name="Carol Del Santo" role="Magazziniere"/>
         </actionStatus>
      </process>
      <process startTime="22/01/2008 16:59 CET">
         <actionStatus action="EmissFattura"/>
      </process>
      <process startTime="20/01/2008 15:06 CET">
         <actionStatus action="EmissFattura" terminationTime="22/01/2008 15:57 CET">
            <actor name="Francesco Messina" role="Contabile"/>
         </actionStatus>
         <actionStatus action="RicezPagamento">
            <actor name="Mario Lamarmora" role="Contabile"/>
         </actionStatus>
      </process>
   </workflow>
</workflowMonitor>

=== broapplication/pd2-sisto/Assignment2/temp1920792534/out872681613.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE workflowMonitor SYSTEM "wfInfo.dtd">
<workflowMonitor>
   <workflow name="RedazioneArticolo">
      <action automaticallyIstantiated="false" name="Revisione" role="Giornalista">
         <simpleAction possibleNextActions="Controllo"/>
      </action>
      <action automaticallyIstantiated="false" name="Controllo" role="Redattore">
         <simpleAction possibleNextActions="Revisione Pubblicazione"/>
      </action>
      <action automaticallyIstantiated="false" name="Pubblicazione" role="Redattore">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="true" name="Scrittura" role="Giornalista">
         <simpleAction possibleNextActions="Controllo"/>
      </action>
   </workflow>
   <workflow name="VenditaNormale">
      <action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
         <simpleAction possibleNextActions="RicezPagamento"/>
      </action>
      <action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="true" name="ConsegnaMerce" role="Magazziniere">
         <simpleAction/>
      </action>
      <process startTime="15/01/2008 19:26 CET">
         <actionStatus action="ConsegnaMerce" terminationTime="15/01/2008 20:19 CET">
            <actor name="Matteo Laviola" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura" terminationTime="15/01/2008 20:05 CET">
            <actor name="Giovanni Milanesi" role="Contabile"/>
         </actionStatus>
         <actionStatus action="RicezPagamento" terminationTime="16/01/2008 18:02 CET">
            <actor name="Monica Perla" role="Contabile"/>
         </actionStatus>
      </process>
      <process startTime="14/01/2008 06:29 CET">
         <actionStatus action="ConsegnaMerce" terminationTime="14/01/2008 16:04 CET">
            <actor name="Maurizio Baldo" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura" terminationTime="15/01/2008 06:55 CET">
            <actor name="Monica Perla" role="Contabile"/>
         </actionStatus>
         <actionStatus action="RicezPagamento" terminationTime="16/01/2008 18:38 CET">
            <actor name="Claudio Castiglia" role="Contabile"/>
         </actionStatus>
      </process>
   </workflow>
   <workflow name="GestioneVendita">
      <action automaticallyIstantiated="true" name="AccettazOrdine" role="AddettoVendite">
         <simpleAction possibleNextActions="VenditaPagAnt VenditaNormale"/>
      </action>
      <action automaticallyIstantiated="false" name="VenditaPagAnt" role="RespVendite">
         <processAction actionWorkflow="VenditaPagAnt"/>
      </action>
      <action automaticallyIstantiated="false" name="VenditaNormale" role="RespVendite">
         <processAction actionWorkflow="VenditaNormale"/>
      </action>
      <process startTime="12/01/2008 20:52 CET">
         <actionStatus action="AccettazOrdine" terminationTime="14/01/2008 13:51 CET">
            <actor name="Maurizio Gonzales" role="AddettoVendite"/>
         </actionStatus>
         <actionStatus action="VenditaNormale" terminationTime="15/01/2008 22:59 CET">
            <actor name="Claude Francese" role="RespVendite"/>
         </actionStatus>
      </process>
   </workflow>
   <workflow name="VenditaPagAnt">
      <action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
         <simpleAction possibleNextActions="RicezPagamento"/>
      </action>
      <action automaticallyIstantiated="false" name="ConsegnaMerce" role="Magazziniere">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
         <simpleAction possibleNextActions="ConsegnaMerce"/>
      </action>
   </workflow>
</workflowMonitor>

=== broapplication/pd2-sisto/Assignment2/temp253813054/out1935348911.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE workflowMonitor SYSTEM "wfInfo.dtd">
<workflowMonitor>
   <workflow name="RedazioneArticolo">
      <action automaticallyIstantiated="false" name="Pubblicazione" role="Redattore">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="false" name="Controllo" role="Redattore">
         <simpleAction possibleNextActions="Revisione Pubblicazione"/>
      </action>
      <action automaticallyIstantiated="true" name="Scrittura" role="Giornalista">
         <simpleAction possibleNextActions="Controllo"/>
      </action>
      <action automaticallyIstantiated="false" name="Revisione" role="Giornalista">
         <simpleAction possibleNextActions="Controllo"/>
      </action>
      <process startTime="12/01/2008 01:32 CET">
         <actionStatus action="Scrittura" terminationTime="13/01/2008 13:04 CET">
            <actor name="Giuseppe Elkan" role="Giornalista"/>
         </actionStatus>
         <actionStatus action="Controllo" terminationTime="13/01/2008 13:31 CET">
            <actor name="Giuseppe Vicentini" role="Redattore"/>
         </actionStatus>
         <actionStatus action="Pubblicazione" terminationTime="14/01/2008 12:34 CET">
            <actor name="Monica Vicentini" role="Redattore"/>
         </actionStatus>
      </process>
      <process startTime="19/01/2008 03:23 CET">
         <actionStatus action="Scrittura" terminationTime="20/01/2008 01:14 CET">
            <actor name="Giuseppe Elkan" role="Giornalista"/>
         </actionStatus>
         <actionStatus action="Controllo" terminationTime="21/01/2008 09:28 CET">
            <actor name="Giuseppe Vicentini" role="Redattore"/>
         </actionStatus>
         <actionStatus action="Pubblicazione" terminationTime="23/01/2008 06:30 CET">
            <actor name="Carlo Marini" role="Redattore"/>
         </actionStatus>
      </process>
   </workflow>
   <workflow name="VenditaNormale">
      <action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
         <simpleAction possibleNextActions="RicezPagamento"/>
      </action>
      <action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="true" name="ConsegnaMerce" role="Magazziniere">
         <simpleAction/>
      </action>
      <process startTime="15/01/2008 18:28 CET">
         <actionStatus action="ConsegnaMerce" terminationTime="16/01/2008 07:22 CET">
            <actor name="Clara Cadorna" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura">
            <actor name="Claudio Minzoni" role="Contabile"/>
         </actionStatus>
      </process>
      <process startTime="13/01/2008 12:52 CET">
         <actionStatus action="ConsegnaMerce"/>
         <actionStatus action="EmissFattura"/>
      </process>
      <process startTime="15/01/2008 08:43 CET">
         <actionStatus action="ConsegnaMerce">
            <actor name="Clara Cadorna" role="Magazziniere"/>
         </actionStatus>
         <actionStatus action="EmissFattura"/>
      </process>
   </workflow>
   <workflow name="GestioneVendita">
      <action automaticallyIstantiated="false" name="VenditaPagAnt" role="RespVendite">
         <processAction actionWorkflow="VenditaPagAnt"/>
      </action>
      <action automaticallyIstantiated="false" name="VenditaNormale" role="RespVendite">
         <processAction actionWorkflow="VenditaNormale"/>
      </action>
      <action automaticallyIstantiated="true" name="AccettazOrdine" role="AddettoVendite">
         <simpleAction possibleNextActions="VenditaPagAnt VenditaNormale"/>
      </action>
      <process startTime="21/01/2008 22:37 CET">
         <actionStatus action="AccettazOrdine" terminationTime="22/01/2008 12:26 CET">
            <actor name="Enrica Lascarpa" role="AddettoVendite"/>
         </actionStatus>
         <actionStatus action="VenditaNormale" terminationTime="23/01/2008 13:40 CET">
            <actor name="Carol Aziz" role="RespVendite"/>
         </actionStatus>
      </process>
   </workflow>
   <workflow name="VenditaPagAnt">
      <action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
         <simpleAction possibleNextActions="RicezPagamento"/>
      </action>
      <action automaticallyIstantiated="false" name="ConsegnaMerce" role="Magazziniere">
         <simpleAction/>
      </action>
      <action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
         <simpleAction possibleNextActions="ConsegnaMerce"/>
      </action>
   </workflow>
</workflowMonitor>

=== broapplication/pd2-sisto/Assignment1/src/dtd/wfInfo.actor-unici.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE workflowMonitor SYSTEM "wfInfo.dtd">
<workflowMonitor>
<workflow name="RedazioneArticolo">
<action automaticallyIstantiated="false" name="Pubblicazione" role="Redattore">
<simpleAction/>
</action>
<action automaticallyIstantiated="false" name="Revisione" role="Giornalista">
<simpleAction possibleNextActions="Controllo"/>
</action>
<action automaticallyIstantiated="true" name="Scrittura" role="Giornalista">
<simpleAction possibleNextActions="Controllo"/>
</action>
<action automaticallyIstantiated="false" name="Controllo" role="Redattore">
<simpleAction possibleNextActions="Revisione Pubblicazione"/>
</action>
<process startTime="12/01/2008 00:58 CET">
<actionStatus action="Scrittura" actor="Anreina Vicentini" terminationTime="12/01/2008 17:15 CET"/>
<actionStatus action="Controllo" actor="Paolo Gonzales" terminationTime="12/01/2008 21:16 CET"/>
<actionStatus action="Pubblicazione" actor="Paolo Gonzales"/>
</process>
<process startTime="18/01/2008 14:21 CET">
<actionStatus action="Scrittura" actor="Anreina Vicentini"/>
</process>
<process startTime="21/01/2008 05:24 CET">
<actionStatus action="Scrittura" actor="Clara Baldo" terminationTime="22/01/2008 17:51 CET"/>
<actionStatus action="Controllo" actor="Maurizio Baldo" terminationTime="24/01/2008 01:32 CET"/>
<actionStatus action="Pubblicazione" actor="Maurizio Baldo" terminationTime="24/01/2008 19:21 CET"/>
</process>
<process startTime="17/01/2008 12:56 CET">
<actionStatus action="Scrittura" actor="Clara Baldo" terminationTime="18/01/2008 14:06 CET"/>
<actionStatus action="Controllo" actor="Francesca Neri" terminationTime="19/01/2008 07:26 CET"/>
<actionStatus action="Revisione" actor="Anreina Vicentini" terminationTime="20/01/2008 11:55 CET"/>
<actionStatus action="Controllo"/>
</process>
<process startTime="14/01/2008 19:11 CET">
<actionStatus action="Scrittura" actor="Anreina Vicentini" terminationTime="16/01/2008 02:24 CET"/>
<actionStatus action="Controllo" actor="Maurizio Baldo" terminationTime="17/01/2008 02:06 CET"/>
<actionStatus action="Revisione" actor="Clara Baldo" terminationTime="17/01/2008 22:13 CET"/>
<actionStatus action="Controllo" actor="Francesca Neri" terminationTime="18/01/2008 15:18 CET"/>
<actionStatus action="Pubblicazione"/>
</process>
<process startTime="23/01/2008 21:53 CET">
<actionStatus action="Scrittura" actor="Elisabeth Carpenteri" terminationTime="25/01/2008 02:16 CET"/>
<actionStatus action="Controllo" actor="Paolo Gonzales" terminationTime="25/01/2008 10:44 CET"/>
<actionStatus action="Revisione" actor="Elisabeth Carpenteri" terminationTime="26/01/2008 14:00 CET"/>
<actionStatus action="Controllo" actor="Maurizio Baldo"/>
</process>
</workflow>
<workflow name="VenditaNormale">
<action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
<simpleAction/>
</action>
<action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
<simpleAction possibleNextActions="RicezPagamento"/>
</action>
<action automaticallyIstantiated="true" name="ConsegnaMerce" role="Magazziniere">
<simpleAction/>
</action>
<process startTime="22/01/2008 17:10 CET">
<actionStatus action="ConsegnaMerce" actor="Enrico Maria Marini"/>
<actionStatus action="EmissFattura" actor="Mario Lagiostra" terminationTime="22/01/2008 19:51 CET"/>
<actionStatus action="RicezPagamento" actor="Caio Baresi"/>
</process>
<process startTime="26/01/2008 23:45 CET">
<actionStatus action="ConsegnaMerce" actor="Sonia Fumagalli" terminationTime="30/01/2008 10:58 CET"/>
<actionStatus action="EmissFattura" actor="Mario Lagiostra" terminationTime="28/01/2008 22:41 CET"/>
<actionStatus action="RicezPagamento" actor="Mario Lagiostra" terminationTime="30/01/2008 04:18 CET"/>
</process>
<process startTime="20/01/2008 22:24 CET">
<actionStatus action="ConsegnaMerce" actor="Sonia Fumagalli"/>
<actionStatus action="EmissFattura" actor="Matteo Tasca" terminationTime="21/01/2008 03:26 CET"/>
<actionStatus action="RicezPagamento"/>
</process>
</workflow>
<workflow name="GestioneVendita">
<action automaticallyIstantiated="false" name="VenditaPagAnt" role="RespVendite">
<processAction actionWorkflow="VenditaPagAnt"/>
</action>
<action automaticallyIstantiated="true" name="AccettazOrdine" role="AddettoVendite">
<simpleAction possibleNextActions="VenditaPagAnt VenditaNormale"/>
</action>
<action automaticallyIstantiated="false" name="VenditaNormale" role="RespVendite">
<processAction actionWorkflow="VenditaNormale"/>
</action>
<process startTime="28/01/2008 08:56 CET">
<actionStatus action="AccettazOrdine" actor="Matteo Messina" terminationTime="28/01/2008 09:34 CET"/>
<actionStatus action="VenditaNormale" actor="Maurizio Carcieri" terminationTime="29/01/2008 06:32 CET"/>
</process>
<process startTime="27/01/2008 07:38 CET">
<actionStatus action="AccettazOrdine"/>
</process>
</workflow>
<workflow name="VenditaPagAnt">
<action automaticallyIstantiated="false" name="ConsegnaMerce" role="Magazziniere">
<simpleAction/>
</action>
<action automaticallyIstantiated="true" name="EmissFattura" role="Contabile">
<simpleAction possibleNextActions="RicezPagamento"/>
</action>
<action automaticallyIstantiated="false" name="RicezPagamento" role="Contabile">
<simpleAction possibleNextActions="ConsegnaMerce"/>
</action>
</workflow>
<actor name="Anreina Vicentini" role="Giornalista"/>
<actor name="Paolo Gonzales" role="Redattore"/>
<actor name="Clara Baldo" role="Giornalista"/>
<actor name="Maurizio Baldo" role="Redattore"/>
<actor name="Francesca Neri" role="Redattore"/>
<actor name="Elisabeth Carpenteri" role="Giornalista"/>
<actor name="Enrico Maria Marini" role="Magazziniere"/>
<actor name="Mario Lagiostra" role="Contabile"/>
<actor name="Caio Baresi" role="Contabile"/>
<actor name="Sonia Fumagalli" role="Magazziniere"/>
<actor name="Matteo Tasca" role="Contabile"/>
<actor name="Matteo Messina" role="AddettoVendite"/>
<actor name="Maurizio Carcieri" role="RespVendite"/>
</workflowMonitor>
