=== broapplication/pd2-sisto/Assignment4/xsd/wfInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/wfInfo"
	xmlns:tns="http://www.example.org/wfInfo" 
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	jaxb:version="1.0"
	elementFormDefault="qualified">
	
	<complexType name="workflowMonitorType">
		
		<sequence>
			<element name="workflow" type="tns:workflowType" maxOccurs="unbounded"
				minOccurs="0">
				<annotation><appinfo>
					<jaxb:property name="workflowList"></jaxb:property>
				</appinfo></annotation>

				<key name="actionNameKey">
					<selector xpath="tns:simpleAction|tns:processAction"></selector>
					<field xpath="@name"></field>
				</key>

				<keyref name="actionStatusKeyref" refer="tns:actionNameKey">
					<selector xpath="tns:process/tns:actionStatus"></selector>
					<field xpath="@action"></field>
				</keyref>

				<keyref name="possibleNextActionKeyref" refer="tns:actionNameKey">
					<selector xpath="tns:simpleAction/tns:possibleNextAction"></selector>
					<field xpath="."></field>
				</keyref>
			</element>
			
		</sequence>

	</complexType>
		

	<element name="workflowMonitor" type="tns:workflowMonitorType">
			
		<key name="workflowNameKey">
			<selector xpath="tns:workflow"></selector>
			<field xpath="@name"></field>
		</key>

		<keyref name="processActionKeyref" refer="tns:workflowNameKey">
			<selector xpath="tns:workflow/tns:processAction"></selector>
			<field xpath="@actionWorkflow"></field>
		</keyref>
	</element>



	<complexType name="workflowType">

		<sequence>
			<choice maxOccurs="unbounded" minOccurs="1">
				<annotation><appinfo>
					<jaxb:property name="actionList"></jaxb:property>
				</appinfo></annotation>
				
				<element name="simpleAction" type="tns:simpleActionType">
					<unique name="dummy1">
						<selector xpath="tns:possibleNextAction"></selector>
						<field xpath="."></field>
					</unique>
				</element>
				<element name="processAction" type="tns:processActionType"></element>
			</choice>
			<element name="process" type="tns:processType" maxOccurs="unbounded"
				minOccurs="0">
				<annotation><appinfo>
					<jaxb:property name="processList"></jaxb:property>
				</appinfo></annotation>
			</element>
		</sequence>

		<attribute name="name" type="tns:idType" use="required"></attribute>
	</complexType>
	
 	<complexType name="actorType">
 		<attribute name="name" type="tns:alphaType" use="required"></attribute>
		<attribute name="role" type="string" use="required"></attribute>
	</complexType>
		
	<complexType name="actionType">
		<attribute name="automaticallyInstantiated" type="boolean"
			default="false"></attribute>
		<attribute name="name" type="tns:idType" use="required"></attribute>
		<attribute name="role" type="string" use="required"></attribute>			
	</complexType>

	<complexType name="processType">
		<sequence>
			<element name="actionStatus" type="tns:actionStatusType"
				maxOccurs="unbounded" minOccurs="0">
				<annotation><appinfo>
					<jaxb:property name="status"></jaxb:property>
				</appinfo></annotation>
			</element>
		</sequence>
		<attribute name="startTime" type="dateTime" use="required"></attribute>
	</complexType>

	<complexType name="simpleActionType">
		<complexContent>
			<extension base="tns:actionType">
				<sequence>
					<element name="possibleNextAction" type="tns:idType"
						maxOccurs="unbounded" minOccurs="0">
						<annotation><appinfo>
							<jaxb:property name="possibleNextActionList"/>
						</appinfo></annotation>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="processActionType">
		<complexContent>
			<extension base="tns:actionType">
				<attribute name="actionWorkflow" type="tns:idType" use="required"/>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="alphaType">
		<restriction base="string">
			<pattern value="[a-zA-Z]|[a-zA-Z][a-zA-Z ]*[a-zA-Z]"></pattern>
		</restriction>
	</simpleType>

	<simpleType name="idType">
		<restriction base="string">
			<pattern value="[a-zA-Z]\w*"></pattern>
		</restriction>
	</simpleType>

	<complexType name="actionStatusType">
		<sequence>
			<element name="actor" type="tns:actorType" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="action" type="tns:idType" use="required">
			<annotation><appinfo>
				<jaxb:property name="actionName"></jaxb:property>
			</appinfo></annotation>
		</attribute>
		<attribute name="terminationTime" type="dateTime"></attribute>
	</complexType>

</schema>

=== broapplication/pd2-sisto/Assignment3/xsd/actor-unici.wfInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<workflowMonitor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/wfInfo" xsi:schemaLocation="http://www.example.org/wfInfo wfInfo.xsd ">
	<workflow name="RedazioneArticolo">
		<simpleAction automaticallyIstantiated="false" name="Controllo"
			role="Redattore">
			<possibleNextAction>Revisione</possibleNextAction>
			<possibleNextAction>Pubblicazione</possibleNextAction>
		</simpleAction>
		<simpleAction automaticallyIstantiated="false" name="Revisione"
			role="Giornalista">
			<possibleNextAction>Controllo</possibleNextAction>
		</simpleAction>
		<simpleAction automaticallyIstantiated="false" name="Pubblicazione"
			role="Redattore" />
		<simpleAction automaticallyIstantiated="true" name="Scrittura"
			role="Giornalista">
			<possibleNextAction>Controllo</possibleNextAction>
		</simpleAction>
		<process startTime="2008-01-29T20:05:00+01:00">
			<actionStatus action="Scrittura" actor="Alessia Piccoli"
				terminationTime="2008-01-30T22:13:00+01:00" />
			<actionStatus action="Controllo" actor="Riccardo Perissino"
				terminationTime="2008-01-31T19:16:00+01:00" />
			<actionStatus action="Pubblicazione" />
		</process>
	</workflow>
	<workflow name="VenditaNormale">
		<simpleAction automaticallyIstantiated="true" name="EmissFattura"
			role="Contabile">
			<possibleNextAction>RicezPagamento</possibleNextAction>
		</simpleAction>
		<simpleAction automaticallyIstantiated="true" name="ConsegnaMerce"
			role="Magazziniere" />
		<simpleAction automaticallyIstantiated="false" name="RicezPagamento"
			role="Contabile" />
		<process startTime="2008-01-17T15:59:00+01:00">
			<actionStatus action="ConsegnaMerce" actor="Eva Trapani" />
			<actionStatus action="EmissFattura" />
		</process>
		<process startTime="2008-01-20T03:06:00+01:00">
			<actionStatus action="ConsegnaMerce" actor="Enrico Maria Verdi"
				terminationTime="2008-01-21T08:23:00+01:00" />
			<actionStatus action="EmissFattura" actor="Mauro Di Crescenzo"
				terminationTime="2008-01-22T05:06:00+01:00" />
			<actionStatus action="RicezPagamento" actor="Anna Baldo" />
		</process>
		<process startTime="2008-01-17T22:19:00+01:00">
			<actionStatus action="ConsegnaMerce" actor="Enrico Maria Verdi" />
			<actionStatus action="EmissFattura" actor="Mauro Di Crescenzo"
				terminationTime="2008-01-19T01:05:00+01:00" />
			<actionStatus action="RicezPagamento" actor="Anna Baldo" />
		</process>
		<process startTime="2008-01-26T21:55:00+01:00">
			<actionStatus action="ConsegnaMerce" />
			<actionStatus action="EmissFattura" />
		</process>
		<process startTime="2008-01-23T19:38:00+01:00">
			<actionStatus action="ConsegnaMerce" actor="Eva Trapani"
				terminationTime="2008-01-26T14:40:00+01:00" />
			<actionStatus action="EmissFattura" actor="Mauro Di Crescenzo"
				terminationTime="2008-01-24T19:57:00+01:00" />
			<actionStatus action="RicezPagamento" actor="Monica Lascarpa" />
		</process>
		<process startTime="2008-01-11T11:18:00+01:00">
			<actionStatus action="ConsegnaMerce" actor="Enrico Maria Verdi"
				terminationTime="2008-01-13T22:05:00+01:00" />
			<actionStatus action="EmissFattura" actor="Mauro Di Crescenzo"
				terminationTime="2008-01-12T16:47:00+01:00" />
			<actionStatus action="RicezPagamento" actor="Mauro Di Crescenzo" />
		</process>
		<process startTime="2008-01-19T05:08:00+01:00">
			<actionStatus action="ConsegnaMerce" actor="Eva Trapani"
				terminationTime="2008-01-19T13:32:00+01:00" />
			<actionStatus action="EmissFattura" actor="Monica Lascarpa"
				terminationTime="2008-01-20T00:43:00+01:00" />
			<actionStatus action="RicezPagamento" actor="Anna Baldo"
				terminationTime="2008-01-20T05:28:00+01:00" />
		</process>
	</workflow>
	<workflow name="GestioneVendita">
		<simpleAction automaticallyIstantiated="true" name="AccettazOrdine"
			role="AddettoVendite">
			<possibleNextAction>VenditaPagAnt</possibleNextAction>
			<possibleNextAction>VenditaNormale</possibleNextAction>
		</simpleAction>
		<processAction automaticallyIstantiated="false" name="VenditaPagAnt"
			role="RespVendite" actionWorkflow="VenditaPagAnt" />
		<processAction automaticallyIstantiated="false" name="VenditaNormale"
			role="RespVendite" actionWorkflow="VenditaNormale" />
		<process startTime="2008-01-18T11:20:00+01:00">
			<actionStatus action="AccettazOrdine" actor="Maurizio Tasca" />
		</process>
		<process startTime="2008-01-15T15:36:00+01:00">
			<actionStatus action="AccettazOrdine" actor="Francesca Pascal"
				terminationTime="2008-01-15T19:18:00+01:00" />
			<actionStatus action="VenditaNormale" />
		</process>
	</workflow>
	<workflow name="VenditaPagAnt">
		<simpleAction automaticallyIstantiated="false" name="ConsegnaMerce"
			role="Magazziniere" />
		<simpleAction automaticallyIstantiated="true" name="EmissFattura"
			role="Contabile">
			<possibleNextAction>RicezPagamento</possibleNextAction>
		</simpleAction>
		<simpleAction automaticallyIstantiated="false" name="RicezPagamento"
			role="Contabile">
			<possibleNextAction>ConsegnaMerce</possibleNextAction>
		</simpleAction>
		<process startTime="2008-01-12T12:11:00+01:00">
			<actionStatus action="EmissFattura" actor="Pier Luigi Castiglia"
				terminationTime="2008-01-13T23:06:00+01:00" />
			<actionStatus action="RicezPagamento" actor="Mario Orafi"
				terminationTime="2008-01-14T07:16:00+01:00" />
			<actionStatus action="ConsegnaMerce" actor="Elisabeth Tasca"
				terminationTime="2008-01-16T02:13:00+01:00" />
		</process>
	</workflow>
	<actor name="Alessia Piccoli" role="Giornalista" />
	<actor name="Riccardo Perissino" role="Redattore" />
	<actor name="Eva Trapani" role="Magazziniere" />
	<actor name="Enrico Maria Verdi" role="Magazziniere" />
	<actor name="Mauro Di Crescenzo" role="Contabile" />
	<actor name="Anna Baldo" role="Contabile" />
	<actor name="Monica Lascarpa" role="Contabile" />
	<actor name="Maurizio Tasca" role="AddettoVendite" />
	<actor name="Francesca Pascal" role="AddettoVendite" />
	<actor name="Pier Luigi Castiglia" role="Contabile" />
	<actor name="Mario Orafi" role="Contabile" />
	<actor name="Elisabeth Tasca" role="Magazziniere" />
</workflowMonitor>
